name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20.9.0-slim
    timeout-minutes: 3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Print versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Run Prettier
        run: npm run lint
